"""
Example: Parser Comment Handling Fix

This example demonstrates that the parser correctly handles .geno files
with mixed comment styles — comments with colons (key:value) and plain
comments without colons.

Before the fix, plain comments like:
    # File entered in GN database on Dec 19, 2018 by Arthur Centeno.
were incorrectly treated as the header row, causing wrong dimensions.

After the fix, ALL # comments are skipped, regardless of whether they
contain a colon.
"""

import tempfile
import shutil
import os

from geno_storage.geno_parser import parse_genotype_file


def create_geno_file(path, content):
    with open(path, 'w') as f:
        f.write(content)


def main():
    temp_dir = tempfile.mkdtemp()
    try:
        # Simulate a real GeneNetwork .geno file with mixed comment styles
        geno_file = os.path.join(temp_dir, "realistic.geno")
        create_geno_file(geno_file, """# File name: BXD_Geno-19Jan2017b_forGN.xls
# Metadata: Please retain this header information with file.
# Data Source and Contact: GeneNetwork at http://www.genenetwork.org
# Citation: Wang X et al. Nature Communications 7:10464
# Date Modified: Dec 19, 2018 by Rob, David Ashbrook, and Danny Arends
# File entered in GN database on Dec 19, 2018 by Arthur Centeno.
# Coordinates of Markers and Assembly: Megabase and basepair positions
# Genotypes: This file provides consensus genotypes for 198 BXD strains
# Material and Cases: 155 BXD strains and substrains are available
# Breeding: BXD1 to BXD30 generated by BA Taylor at the Jackson Laboratory
# Errors and Corrections: This file contains genotyping errors
# Funding: This work and GeneNetwork have been funded by The UTHSC
# Column Heads: Chr = chromosome, Locus=marker name
@name:BXD
@type:riset
@mat:B
@pat:D
@het:H
@unk:U
Chr\tLocus\tcM\tMb\tBXD1\tBXD2\tBXD3\tBXD4\tBXD5
1\trs31443144\t1.50\t3.010274\tB\tB\tD\tD\tD
1\trs6269442\t1.50\t3.492195\tB\tB\tD\tD\tD
1\trs32285189\t1.63\t3.511204\tB\tB\tD\tD\tD
2\trs13478224\t0.00\t5.000000\tD\tD\tB\tB\tB
2\trs13478397\t0.50\t5.500000\tH\tH\tB\tB\tD
""")

        print("=== Parsing realistic .geno with mixed comment styles ===")
        genotype = parse_genotype_file(geno_file)

        print(f"Dataset: {genotype.dataset_name}")
        print(f"Type: {genotype.cross_type}")
        print(f"Founders: {genotype.founders}")
        print(f"Matrix shape: {genotype.matrix.shape}")
        print(f"Markers ({len(genotype.markers)}): {genotype.markers}")
        print(f"Samples ({len(genotype.samples)}): {genotype.samples}")
        print(f"Chromosomes: {genotype.chromosomes}")
        print(f"Positions: {genotype.positions}")
        print(f"Allele map: {genotype.allele_map}")

        assert genotype.matrix.shape == (5, 5), f"Expected (5, 5), got {genotype.matrix.shape}"
        assert genotype.samples == ["BXD1", "BXD2", "BXD3", "BXD4", "BXD5"]
        assert genotype.markers == ["rs31443144", "rs6269442", "rs32285189", "rs13478224", "rs13478397"]
        print("\n✓ All assertions passed — parser correctly skipped all # comments")

    finally:
        shutil.rmtree(temp_dir, ignore_errors=True)


if __name__ == "__main__":
    main()
